config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  root "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :exercise_category
  resources :users
  resources :exercises
  namespace :api do
    resources :exercises
  end
  resources :workouts
  namespace :api do
    resources :workouts
  end
  get "/select_user", to: "users#select", as: "select_user"
  post "/set_user", to: "users#set_user", as: "set_user"
  delete "/logout", to: "users#logout", as: "logout"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :exercise_category

  has_many :workout_exercises
  has_many :workouts, through: :workout_exercises

  validates :name, presence: true, length: { maximum: 64 }
  validates :exercise_category, presence: true
end

app/models/exercise_category.rb
class ExerciseCategory < ApplicationRecord
  has_many :exercises
end

app/models/normal_set.rb
class NormalSet < ApplicationRecord
end

app/models/pyramid_set.rb
class PyramidSet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :workouts
  validates :username, presence: true, length: { maximum: 16 }, uniqueness: true
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :workout_exercises, dependent: :destroy
  has_many :exercises, through: :workout_exercises

  before_save :set_default_name

  private

  def set_default_name
    if self.title.blank?
      workout_count = user.workouts.count + 1
      self.title = "New Workout #{workout_count}"
    end
  end
end

app/models/workout_exercise.rb
class WorkoutExercise < ApplicationRecord
  belongs_to :exercise
  belongs_to :workout
  # belongs_to :set_variation, polymorphic: true
  validates :exercise, presence: true
  validates :workout, presence: true
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ActionController::API
    # Define any common behavior for your API controllers here
  end
end

app/controllers/api/exercises_controller.rb
module Api
  class ExercisesController < BaseController
    def index
      @exercises = Exercise.all
      render json: @exercises
    end

    def show
      @exercise = Exercise.find(params[:id])
      render json: @exercise
    end

    def new
      @exercise = Exercise.new
    end

    def create
      @exercise = Exercise.new(exercise_params)

      if @exercise.save
        flash[:notice] = "Exercise was successfully created."
        redirect_to @exercise
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @exercise = Exercise.find(params[:id])
    end

    def update
      @exercise = Exercise.find(params[:id])

      if @exercise.update(exercise_params)
        flash[:notice] = "Exercise was successfully updated."
        redirect_to @exercise
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @exercise = Exercise.find(params[:id])
      @exercise.destroy

      redirect_to exercises_path, status: :see_other
    end

    private
      def exercise_params
        params.require(:exercise).permit(:name, :exercise_category_id)
      end
  end
end

app/controllers/api/workouts_controller.rb
module Api
  class WorkoutsController < BaseController
    def index
      @workouts = Workout.includes(:user)
      render json: @workouts.as_json(include: { user: { only: :username } })
    end

    def show
      @workout = Workout.find(params[:id])
      @exercises = @workout.exercises
    end

    def new
      @workout = Workout.new
    end

    def create
      @workout = Workout.new(workout_params)

      if @workout.save
        create_workout_exercises(@workout, params[:workout][:exercise_ids])
        redirect_to @workout, notice: "Workout was successfully created."
      else
        render :new
      end
    end

    def destroy
      @workout = Workout.find(params[:id])
      @workout.destroy

      redirect_to workouts_path, status: :see_other
    end

    private

    def workout_params
      params.require(:workout).permit(:user_id)
    end

    def create_workout_exercises(workout, exercise_ids)
      exercise_ids.reject(&:blank?).each do |exercise_id|
        WorkoutExercise.create(workout_id: workout.id, exercise_id: exercise_id)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
  helper_method :current_user

  before_action :ensure_user_selected

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def ensure_user_selected
    unless current_user
      redirect_to select_user_path unless request.path == select_user_path
    end
  end
end

app/controllers/exercise_categories_controller.rb
class ExerciseCategoriesController < ApplicationController
  def index
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercises = Exercise.all
  end

  def show
    @exercise = Exercise.find(params[:id])
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = Exercise.new(exercise_params)

    if @exercise.save
      flash[:notice] = "Exercise was successfully created."
      redirect_to @exercise
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @exercise = Exercise.find(params[:id])
  end

  def update
    @exercise = Exercise.find(params[:id])

    if @exercise.update(exercise_params)
      flash[:notice] = "Exercise was successfully updated."
      redirect_to @exercise
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @exercise = Exercise.find(params[:id])
    @exercise.destroy

    redirect_to exercises_path, status: :see_other
  end

  private
    def exercise_params
      params.require(:exercise).permit(:name, :exercise_category_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_selected, only: [ :select, :set_user ]
  def index
    @users = User.all
  end
  def select
    @users = User.all
  end

  def set_user
    session[:user_id] = params[:user_id]
    redirect_to pages_home_path
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
    @workouts = Workout.all
  end

  def show
    @workout = Workout.find(params[:id])
    @exercises = @workout.exercises
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)

    if @workout.save
      create_workout_exercises(@workout, params[:workout][:exercise_ids])
      redirect_to @workout, notice: "Workout was successfully created."
    else
      render :new
    end
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy

    redirect_to workouts_path, status: :see_other
  end

  private

  def workout_params
    params.require(:workout).permit(:user_id)
  end

  def create_workout_exercises(workout, exercise_ids)
    exercise_ids.reject(&:blank?).each do |exercise_id|
      WorkoutExercise.create(workout_id: workout.id, exercise_id: exercise_id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercise_categories_helper.rb
module ExerciseCategoriesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercise_category/index.html.erb
<div>
  <h1 class="font-bold text-4xl">ExerciseCategories#index</h1>
  <p>Find me in app/views/exercise_category/index.html.erb</p>
</div>

app/views/exercises/_form.html.erb
<%= form_with model: exercise, class: "space-y-6" do |form| %>
  <div class="space-y-2">
    <%= form.label :name, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :name, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-spartan-red-500 focus:border-spartan-red-500 sm:text-sm" %>
    <% exercise.errors.full_messages_for(:name).each do |msg| %>
      <p class="text-red-500 text-sm"><%= msg %></p>
    <% end %>
  </div>
  <div class="space-y-2">
    <%= form.label :exercise_category_id, class: "block text-sm font-medium text-gray-700" %>
    <%= form.collection_select :exercise_category_id, ExerciseCategory.all, :id, :title, { include_blank: true }, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:spartan-red-500 focus:spartan-red-500 sm:text-sm" %>
    <% exercise.errors.full_messages_for(:exercise_category).each do |msg| %>
      <p class="text-red-500 text-sm"><%= msg %></p>
    <% end %>
  </div>
  <div>
    <%= form.submit "Create Exercise", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-spartan-red-600 hover:bg-spartan-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1 class="text-2xl font-bold mb-4">Edit Exercise</h1>

<%= render "form", exercise: @exercise %>

app/views/exercises/index.html.erb
<div class="flex flex-col">
<div class="p-4 bg-gold-100 rounded-xl">
  <h1 class="font-bold text-4xl text-center text-spartan-red-600">Exercises#index</h1>

  <h2 class="font-bold text-5xl text-spartan-red-400">Exercises</h2>
  <ul>
    <% @exercises.each do |exercise| %>
    <li>
      <%= link_to exercise.name, exercise %>
    </li>
    <% end %>
  </ul>
</div>

<%= link_to "New Exercise", new_exercise_path, class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-spartan-red-600 hover:bg-spartan-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-spartan-red-500" %>
</div>

app/views/exercises/new.html.erb
<h1 class="text-2xl font-bold mb-4">New Exercise</h1>

<%= render "form", exercise: @exercise %>

app/views/exercises/show.html.erb
<div class="flex flex-col">
    <div class="p-4 bg-gold-100 rounded-xl">
        <h2 class="font-bold text-5xl text-spartan-red-400">Exercise Details</h2>
        <div class="space-y-2">
            <p>
                <span class="font-bold">Name:</span>
                <%= @exercise.name %>
            </p>
            <p>
                <span class="font-bold">Category:</span>
                                <% if @exercise.exercise_category %>
                  <%= @exercise.exercise_category.title %>
                <% else %>
                  <span class="text-red-500">No category assigned</span>
                <% end %>
            </p>
        </div>

                <div>
          <p>
            <span class="font-bold">Category:</span>
            <% if @exercise.exercise_category %>
              <%= @exercise.exercise_category.title %>
            <% else %>
              <span class="text-red-500">No category assigned</span>
            <% end %>
          </p>
        </div>
        
        <ul class="flex space-x-4 mt-4">
          <li>
            <%= link_to "Edit", edit_exercise_path(@exercise), class: "text-spartan-red-500 underline hover:text-blue-700" %>
          </li>
          <li>
            <%= link_to "Back", exercises_path, class: "text-spartan-red-500 underline hover:text-blue-700" %>
          </li>
          
          
          <%# Please fix this %>
          <%# <li><%= link_to "Destroy", exercise_path(@exercise), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li> 

            <li>
            <%= button_to 'Delete', exercise_path(@exercise), method: :delete, class: "text-red-500 underline hover:text-red-700" %>
            </li>
        </ul>

    </div>
</div>

app/views/users/index.html.erb
<div class="p-4 bg-gray-100 rounded-lg hover:shadow-lg">
    
  <h1 class="font-bold text-4xl">Choose your fighter</h1>

    <h2 class="font-bold text-5xl text-green-400">Users</h2>
    <ul>
      <% @users.each do |user| %>
      <li>
        <%= link_to user.username, user %>
      </li>
      <% end %>
    </ul>

    <h2 class="font-bold text-5xl text-green-400">Exercises</h2>
    <p>
            <%= link_to "Exercises", exercises_path, class: "text-blue-500 underline hover:text-blue-700" %>
    </p>
</div>

app/views/users/select.html.erb
<h1>Select a User</h1>
<%= form_with url: set_user_path, method: :post do %>
  <%= select_tag :user_id, options_from_collection_for_select(@users, :id, :username) %>
  <%= submit_tag "Next" %>
<% end %>

app/views/users/show.html.erb
<div className="p-4 bg-gray-100 rounded-lg">
    <h1>
        <%= @user.username %>
    </h1>
    <p>Created at: <%= @user.created_at.strftime("%B %d, %Y") %></p>
</div>

app/views/workouts/index.html.erb
<div class="flex flex-col">
  <h1 class="text-2xl font-bold mb-4">My Past Workouts</h1>

  <% if current_user %>
    <div class="mb-8">
      <% my_workouts = @workouts.select { |workout| workout.user_id == current_user.id } %>
      <% if my_workouts.any? %>
        <% my_workouts.each do |workout| %>
          <p class="mb-2">
            <strong>
              <%= link_to workout.title, workout_path(workout), class: "text-blue-700 underline" %>
            </strong> - <%= workout.created_at.strftime("%B %d, %Y %H:%M") %>
          </p>
        <% end %>
      <% else %>
        <p>You have no past workouts.</p>
      <% end %>
    </div>
  <% else %>
    <p>Please select a user to view your workouts.</p>
  <% end %>

  <h1 class="text-2xl font-bold mb-4">Workouts from Other Users</h1>

  <div>
    <% other_workouts = @workouts.reject { |workout| workout.user_id == current_user&.id } %>
    <% if other_workouts.any? %>
      <% other_workouts.each do |workout| %>
        <p class="mb-2">
          <strong>
            <%= link_to workout.title, workout_path(workout), class: "text-blue-700 underline" %>
          </strong> - <%= workout.created_at.strftime("%B %d, %Y %H:%M") %> by <%= workout.user.username %>
        </p>
      <% end %>
    <% else %>
      <p>There are no workouts from other users.</p>
    <% end %>
  </div>

  <div class="mt-8">
    <%= link_to "New Workout", new_workout_path, class: "text-blue-700 underline" %>
  </div>
</div>

app/views/workouts/new.html.erb
<div class="w-full"> 
  <h1 class="font-bold text-red-400 text-center text-4xl">New Workout</h1>
  <div class="bg-gold-100 p-4 w-full rounded-3xl"> 
    <%= form_with model: @workout, local: true do |form| %>

      <div class="field mb-4">
        <%= form.hidden_field :user_id, value: current_user.id %>
      </div>
      

      <div class="field mb-4">
        <%= form.label :exercises, class: "block text-lg font-medium text-spartan-grey-500 mb-2" %>
        <div class="bg-white border border-spartan-grey-500 rounded-lg p-4">
          <%= collection_check_boxes(:workout, :exercise_ids, Exercise.all, :id, :name) do |b| %>
            <div class="flex items-center mb-2">
              <%= b.check_box(class: "form-checkbox h-5 w-5 text-spartan-red-400") %>
              <%= b.label(class: "ml-2 text-spartan-grey-500") %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit "Create Workout", class: "bg-spartan-red-400 text-white font-bold py-2 px-4 rounded hover:bg-gold-500" %>
      </div>
    <% end %>
  <div> 
</div>

app/views/workouts/show.html.erb
<div>
    <h1 class="text-3xl font-bold text-spartan-red mb-6"><%= @workout.title %></h1>

    <h2 class="text-2xl font-semibold text-spartan-red mb-4">Exercises</h2>
    <ul class="list-disc list-inside">
    <% @exercises.each do |exercise| %>
        <li class="text-lg text-spartan-grey mb-2"><%= exercise.name %></li>
    <% end %>
    </ul>

    <%= button_to 'Delete Workout', workout_path(@workout), method: :delete, class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded' %>
<div>